# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "render-sample-app"
client_id = "5133a6ed7af02bb87be53e61ffac60d3"
application_url = "https://mathematical-hopes-webpage-tions.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mathematical-hopes-webpage-tions.trycloudflare.com/auth/callback",
  "https://mathematical-hopes-webpage-tions.trycloudflare.com/auth/shopify/callback",
  "https://mathematical-hopes-webpage-tions.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-62ba6ee3.myshopify.com"
